repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2 # must match requirements-tests.txt
    hooks:
      - id: pycln
        args: [--config=pyproject.toml, stubs, stdlib, tests, scripts]
  - repo: https://github.com/psf/black
    rev: 22.12.0 # must match requirements-tests.txt
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4 # must match requirements-tests.txt
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # must match requirements-tests.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear==22.12.6" # must match requirements-tests.txt
          - "flake8-noqa==1.3.0" # must match requirements-tests.txt
          - "flake8-pyi==22.11.0" # must match requirements-tests.txt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [yaml]

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [flake8]
  submodules: false
