name: Post mypy_primer comment

on:
  workflow_run:
    workflows:
      - Run mypy_primer
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    name: Comment PR from mypy_primer
    runs-on: ubuntu-latest
    steps:
      - name: Download diffs
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            console.log({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            console.log(artifacts);
            console.log(artifacts.data);
            console.log(artifacts.data.artifacts);
            console.log(artifacts.data.artifacts.map(a => a.name));
            const matchArtifact = artifacts.data.artifacts.filter((artifact) =>
              artifact.name == "mypy_primer_diffs")[0];
            console.log(matchArtifacts);
            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: "zip",
            });
            fs.writeFileSync("${{github.workspace}}/diff.zip", Buffer.from(download.data));
      - run: unzip diff.zip

      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const data = (
              ['diff_0.txt', 'diff_1.txt']
              .map(fileName => fs.readFileSync(fileName, { encoding: 'utf8' }))
              .join('')
              .substr(0, 30000)  // About 300 lines
            )

            console.log("Diff from mypy_primer:")
            console.log(data)

            let body
            if (data.trim()) {
              body = 'Diff from [mypy_primer](https://github.com/hauntsaninja/mypy_primer), showing the effect of this PR on open source code:\n```diff\n' + data + '```'
            } else {
              body = 'According to [mypy_primer](https://github.com/hauntsaninja/mypy_primer), this change has no effect on the checked open source code. ðŸ¤–ðŸŽ‰'
            }

            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - uses: kanga333/comment-hider@9141763feccc8da773595675adc567d6616b6e6f
        name: Hide old comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leave_visible: 1
